### ISSUE TITLE
Custom Yggdrasil API URL Editing in Minecraft Launcher

### ISSUE THREAD

**Issue by Aocro** [l1ttleO/PrismLauncher-elyby#5]
### Role

I play modded Minecraft with external authentication server.

### Suggestion

I propose adding a setting page, such as the Account page or a dedicated settings section, where users can enter and modify we preferred authentication server URL.

### Benefit

Compatibility with different authentication servers without being restricted to Microsoft or Ely.by authentication servers.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Octol1ttle** [comment]
Unfortunately, that is not the goal of this fork. This fork was created because I wanted a good fork of PrismLauncher that had specifically Ely.by accounts. My approach is to make as little changes to the codebase as possible to make updating easy and avoid potential compatibility issues. The proposed idea falls out of scope for that approach
